services:
  - type: web
    name: ccs-sentiment-app
    runtime: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn app.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: X_BEARER_TOKEN
        sync: false
      - key: ANTHROPIC_API_KEY
        sync: false
